-- One-time seed of stitch_metadata from the current hardcoded
-- STITCH_LIBRARY (crochet, index.html:1020-1084) and KNIT_SYMS (knit,
-- index.html:3994-4058). Cosmetic fields only (display_name/short_name/
-- category) -- geometry/w/h/file is intentionally not part of this table
-- at all. description/instructions left null for admin to fill in later.

begin;

insert into public.stitch_metadata (stitch_key, craft, category, display_name, short_name) values
-- crochet: STITCH_LIBRARY
('ch','crochet','basic','Chain','ch'),
('sc','crochet','basic','Single Crochet','SC'),
('hdc','crochet','basic','Half Double Crochet','HDC'),
('dc','crochet','basic','Double Crochet','DC'),
('tr','crochet','basic','Treble Crochet','TR'),
('inc','crochet','basic','Increase (2-in-1)','Increase'),
('dec','crochet','basic','Decrease (2tog)','Decrease'),
('mr','crochet','basic','Magic Ring','MR'),
('dtr','crochet','advanced','Double Treble','dtr'),
('slst','crochet','advanced','Slip Stitch','sl st'),
('3dccluster','crochet','advanced','3-dc Cluster','3dc Cluster'),
('4dccluster','crochet','advanced','4-dc Cluster','4dc Cluster'),
('3hdccluster','crochet','advanced','3-hdc Cluster','3hdc Cluster'),
('4trcluster','crochet','advanced','4-tr Cluster','4tr Cluster'),
('2dccluster','crochet','advanced','2-dc Cluster','2dc Cluster'),
('2hdccluster','crochet','advanced','2-hdc Cluster','2hdc Cluster'),
('2trcluster','crochet','advanced','2-tr Cluster','2tr Cluster'),
('3trcluster','crochet','advanced','3-tr Cluster','3tr Cluster'),
('5hdcpopcorn','crochet','advanced','5-hdc Popcorn','5hdc Pop'),
('5dcpopcorn','crochet','advanced','5-dc Popcorn','5dc Pop'),
('5trpopcorn','crochet','advanced','5-tr Popcorn','5tr Pop'),
('5hdcpuff','crochet','advanced','5-hdc Puff','5hdc Puff'),
('5dcpuff','crochet','advanced','5-dc Puff','5dc Puff'),
('5trpuff','crochet','advanced','5-tr Puff','5tr Puff'),
('5hdcshell','crochet','advanced','5-hdc Shell','5hdc Shell'),
('5dcshell','crochet','advanced','5-dc Shell','5dc Shell'),
('scblo','crochet','advanced','SC Back Loop Only','sc blo'),
('scflo','crochet','advanced','SC Front Loop Only','sc flo'),
('sc2tog','crochet','advanced','SC 2 Together','sc2tog'),
('sc3tog','crochet','advanced','SC 3 Together','sc3tog'),
('dc2tog','crochet','advanced','DC 2 Together','dc2tog'),
('dc3tog','crochet','advanced','DC 3 Together','dc3tog'),
('dc4tog','crochet','advanced','DC 4 Together','dc4tog'),
('hdc2tog','crochet','advanced','HDC 2 Together','hdc2tog'),
('hdc3tog','crochet','advanced','HDC 3 Together','hdc3tog'),
('hdc4tog','crochet','advanced','HDC 4 Together','hdc4tog'),
('picot','crochet','advanced','3-Chain Picot','picot'),
('fpsc','crochet','advanced','Front Post SC','fp sc'),
('fphdc','crochet','advanced','Front Post HDC','fp hdc'),
('fpdc','crochet','advanced','Front Post DC','fp dc'),
('fptr','crochet','advanced','Front Post TR','fp tr'),
('bpsc','crochet','advanced','Back Post SC','bp sc'),
('bphdc','crochet','advanced','Back Post HDC','bp hdc'),
('bpdc','crochet','advanced','Back Post DC','bp dc'),
('bpdtr','crochet','advanced','Back Post DTR','bp dtr'),
('cdc','crochet','advanced','Crossed DC','x dc'),
('chdc','crochet','advanced','Crossed HDC','x hdc'),
('ctr','crochet','advanced','Crossed TR','x tr'),
('shell','crochet','group','Fan sts into same base','Shell'),
('cluster','crochet','group','Sts joined at top','Cluster'),
('puff','crochet','group','Puff stitch','Puff'),
('vch','crochet','structure','Vertical Chain','vch'),
('ch3_arch','crochet','structure','Chain-3 Space','Ch Arc 3'),
('ch2','crochet','structure','2 Chains','ch x2'),
('ch3','crochet','structure','3 Chains','ch x3'),
('ch4','crochet','structure','4 Chains','ch x4'),
('ch5','crochet','structure','5 Chains','ch x5'),
-- knit: KNIT_SYMS
('k','knit','basic','Knit','K'),
('p','knit','basic','Purl','P'),
('ktbl','knit','basic','Knit TBL','ktbl'),
('ptbl','knit','basic','Purl TBL','ptbl'),
('bo','knit','basic','Bind Off','BO'),
('nostitch','knit','basic','No Stitch','—'),
('ktbls','knit','more','Knit TBL Straight','ktbl2'),
('yo','knit','yo','Yarn Over','YO'),
('yotw','knit','yo','YO Twisted','YOT'),
('m1l','knit','increase','Make 1 Left','M1L'),
('m1r','knit','increase','Make 1 Right','M1R'),
('inc1to3','knit','increase','1 into 3','kyk'),
('ssk','knit','decrease','SSK','ssk'),
('ssp','knit','decrease','SSP','ssp'),
('k2tog','knit','decrease','K2tog','k2tog'),
('p2tog','knit','decrease','P2tog','p2tog'),
('sk2p','knit','decrease','SK2P','sk2p'),
('sssk','knit','decrease','SSSK','sssk'),
('k3tog','knit','decrease','K3tog','k3tog'),
('dec4l','knit','decrease','Dec 4→1 L','dec4l'),
('dec4r','knit','decrease','Dec 4→1 R','dec4r'),
('dec5c','knit','decrease','Dec 5→1 C','dec5c'),
('dec5l','knit','decrease','Dec 5→1 L','dec5l'),
('dec5r','knit','decrease','Dec 5→1 R','dec5r'),
('dec7','knit','decrease','Dec 7→1','dec7'),
('dec7l','knit','decrease','Dec 7→1 L','dec7l'),
('dec7r','knit','decrease','Dec 7→1 R','dec7r'),
('ssk2w','knit','more','SSK (wide)','ssk'),
('k2tog2w','knit','more','K2tog (wide)','k2tog'),
('sl1','knit','slip','Slip 1','sl1'),
('sl1wyif','knit','slip','Slip wyif','sl1wyif'),
('passL','knit','slip','Pass Left','passL'),
('passR','knit','slip','Pass Right','passR'),
('slL','knit','more','Slant Left','slL'),
('slR','knit','more','Slant Right','slR'),
('dip','knit','dip','Dip Stitch','dip'),
('dipp','knit','dip','Dip Purl','dipP'),
('dipTw','knit','dip','Dip Twist','dipTw'),
('crossL','knit','twist','Cross Left (RT)','RT'),
('crossLp','knit','twist','Cross Left Purl','RTP'),
('crossR','knit','twist','Cross Right (LT)','LT'),
('crossRp','knit','twist','Cross Right Purl','LTP'),
('twL','knit','twist','Twist Left','T2L'),
('twLp','knit','twist','Twist Left Purl','T2LP'),
('twR','knit','twist','Twist Right','T2R'),
('twRp','knit','twist','Twist Right Purl','T2RP'),
('c2o1l','knit','cable','2/1 LC','2/1LC'),
('c2o1lp','knit','cable','2/1 LPC','2/1LPC'),
('c2o1r','knit','cable','2/1 RC','2/1RC'),
('c2o1rp','knit','cable','2/1 RPC','2/1RPC'),
('c4f','knit','cable','C4 Front','C4F'),
('c4fp','knit','cable','C4 Front Purl','C4FP'),
('c4b','knit','cable','C4 Back','C4B'),
('c4bp','knit','cable','C4 Back Purl','C4BP')
on conflict (stitch_key) do nothing;

commit;
